# Generated by Django 2.0.4 on 2018-04-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_edificio', models.CharField(max_length=15)),
                ('no_apartamento', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagos', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('cedula', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Residencial.Residente'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Residencial.Residente'),
        ),
    ]
