# Generated by Django 2.0.4 on 2018-04-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='no_edificio',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Residencial.Apartamento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pagos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='residente',
            name='correo',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
