# Generated by Django 2.0.4 on 2018-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0002_auto_20180418_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='residente',
            name='propietario',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='residente',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
