# Generated by Django 2.0.4 on 2018-04-26 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0003_auto_20180418_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='concepto',
            field=models.CharField(default='N/A', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='concepto_deuda',
            field=models.CharField(default='N/A', max_length=70),
        ),
        migrations.AddField(
            model_name='pago',
            name='deuda_peniente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='recargo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='pagos',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
