# Generated by Django 2.0.4 on 2018-04-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0004_auto_20180426_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residente',
            old_name='propietario',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='residente',
            name='edificio',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residente',
            name='no_apartamento',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residente',
            name='cedula',
            field=models.CharField(max_length=11),
        ),
    ]
