# Generated by Django 2.0.4 on 2018-04-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0005_auto_20180427_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='deuda_peniente',
            new_name='deuda_pendiente',
        ),
    ]
