# Generated by Django 2.0 on 2018-05-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0007_auto_20180503_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Para_Facturar', models.DateField(auto_now_add=True, verbose_name='Fecha para Facturar')),
                ('monto_Manteniento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_Limite_Pago', models.DateField(auto_now_add=True, verbose_name='Fecha Limite de Pago')),
                ('recargo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
