# Generated by Django 2.0 on 2018-05-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0008_ajuste_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajuste',
            old_name='recargo',
            new_name='pago_Recargo',
        ),
    ]
