# Generated by Django 2.0 on 2018-05-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0009_auto_20180503_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuste',
            name='fecha_Limite_Pago',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha_Limite_de_Pago'),
        ),
    ]
