# Generated by Django 2.0 on 2018-05-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0010_auto_20180503_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuste',
            name='fecha_Limite_Pago',
            field=models.DateField(blank=True, verbose_name='Fecha_Limite_de_Pago'),
        ),
        migrations.AlterField(
            model_name='ajuste',
            name='fecha_Para_Facturar',
            field=models.DateField(blank=True, verbose_name='Fecha para Facturar'),
        ),
    ]
