# Generated by Django 2.0 on 2018-07-19 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0012_auto_20180503_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Residencial.Estado'),
        ),
    ]
