# Generated by Django 2.0 on 2018-09-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0015_auto_20180827_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.IntegerField()),
                ('apartamento', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='sugerencia',
            field=models.TextField(),
        ),
    ]
