# Generated by Django 2.0 on 2018-09-25 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0016_auto_20180922_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='correo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residente',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
