# Generated by Django 2.0 on 2018-09-27 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0019_auto_20180924_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='correo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
