# Generated by Django 2.0 on 2018-09-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residencial', '0020_auto_20180927_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='correo',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
